package pseudorandom;


import dataanalyzer.gui.IAlgorithmPanel;

/*
 * PPseudoRandom.java
 *
 * Created on 19 March 2009, 11:36
 */
/**
 *
 * @author  davnei06
 */
public class PPseudoRandom extends IAlgorithmPanel {

    private PseudoRandom pseudoRandom;

    /** Creates new form PPseudoRandom */
    public PPseudoRandom(PseudoRandom pseudoRandom) {
        this.pseudoRandom = pseudoRandom;
        initComponents();
    }

    public void collectInput() {
        pseudoRandom.dispose();
        pseudoRandom.collectInput(Integer.valueOf(tfMin.getText()));
        pseudoRandom.collectInput(Integer.valueOf(tfMax.getText()));
        pseudoRandom.collectInput(Integer.valueOf(tfSeed.getText()));
        pseudoRandom.collectInput(Integer.valueOf(tfStep.getText()));
        pseudoRandom.collectInput(Integer.valueOf(tfMinLimit.getText()));
        pseudoRandom.collectInput(Integer.valueOf(tfMaxLimit.getText()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        lMin = new javax.swing.JLabel();
        tfMin = new javax.swing.JTextField();
        lMax = new javax.swing.JLabel();
        lSeed = new javax.swing.JLabel();
        lStep = new javax.swing.JLabel();
        tfMax = new javax.swing.JTextField();
        tfSeed = new javax.swing.JTextField();
        tfStep = new javax.swing.JTextField();
        tfMinLimit = new javax.swing.JTextField();
        tfMaxLimit = new javax.swing.JTextField();
        lMaxLimit = new javax.swing.JLabel();
        lMinLimit = new javax.swing.JLabel();

        lTitle.setFont(new java.awt.Font("Tahoma", 0, 36));
        lTitle.setText("Pseudo Random");

        lMin.setText("Minimum value:");

        tfMin.setText("1");

        lMax.setText("Maximum value:");

        lSeed.setText("Seed:");

        lStep.setText("Step:");

        tfMax.setText("1000");

        tfSeed.setText("1");

        tfStep.setText("1");

        tfMinLimit.setText("-128");

        tfMaxLimit.setText("127");

        lMaxLimit.setText("Maximum limit:");

        lMinLimit.setText("Minimum limit:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lMin)
                            .addComponent(lMax)
                            .addComponent(lSeed)
                            .addComponent(lStep)
                            .addComponent(lMinLimit)
                            .addComponent(lMaxLimit))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMaxLimit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(tfMinLimit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(tfStep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(tfSeed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(tfMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(tfMax, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMin)
                    .addComponent(tfMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMax)
                    .addComponent(tfMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSeed)
                    .addComponent(tfSeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStep)
                    .addComponent(tfStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMinLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lMinLimit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMaxLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lMaxLimit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lMax;
    private javax.swing.JLabel lMaxLimit;
    private javax.swing.JLabel lMin;
    private javax.swing.JLabel lMinLimit;
    private javax.swing.JLabel lSeed;
    private javax.swing.JLabel lStep;
    private javax.swing.JLabel lTitle;
    private javax.swing.JTextField tfMax;
    private javax.swing.JTextField tfMaxLimit;
    private javax.swing.JTextField tfMin;
    private javax.swing.JTextField tfMinLimit;
    private javax.swing.JTextField tfSeed;
    private javax.swing.JTextField tfStep;
    // End of variables declaration//GEN-END:variables
}
