/*
 * PCounter.java
 *
 * Created on 30 March 2009, 16:44
 */

package basicalgorithms;

import dataanalyzer.gui.IAlgorithmPanel;

/**
 *
 * @author  Petah
 */
public class PCounter extends IAlgorithmPanel {

    private Counter counter;

    /** Creates new form PPseudoRandom */
    public PCounter(Counter counter) {
        this.counter = counter;
        initComponents();
    }

    public void collectInput() {
        counter.dispose();
        counter.collectInput(Long.valueOf(tfTime.getText()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        lTime = new javax.swing.JLabel();
        tfTime = new javax.swing.JTextField();

        lTitle.setFont(new java.awt.Font("Tahoma", 0, 36));
        lTitle.setText("Counter");

        lTime.setText("Time (seconds):");

        tfTime.setText("5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lTime)
                        .addGap(18, 18, 18)
                        .addComponent(tfTime, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTime)
                    .addComponent(tfTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lTime;
    private javax.swing.JLabel lTitle;
    private javax.swing.JTextField tfTime;
    // End of variables declaration//GEN-END:variables

}
