/*
 * PLZW.java
 *
 * Created on 19 March 2009, 11:12
 */
package lzw;

import compression.util.CompressionTask;
import dataanalyzer.gui.IAlgorithmPanel;
import dataanalyzer.interfaces.ISystem;
import dataanalyzer.listeners.SystemListener;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author  davnei06
 */
public class PLZW extends IAlgorithmPanel implements SystemListener {

    private LZW lzw;
    private Object input;

    /** Creates new form PLZW */
    public PLZW(LZW a) {
        this.lzw = a;
        initComponents();
    }

    @Override
    public void collectInput() {
        lzw.dispose();
        if (rCompress.isSelected()) {
            lzw.collectInput(CompressionTask.COMPRESS);
        } else {
            lzw.collectInput(CompressionTask.DECOMPRESS);
        }
        lzw.collectInput(input);
    }

    public void collectObject(Object o) {
        input = o;
        tfIn.setText(input.toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfIn = new javax.swing.JTextField();
        bChoose = new javax.swing.JButton();
        rCompress = new javax.swing.JRadioButton();
        rDecompress = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36));
        jLabel1.setText("LZW");

        jLabel2.setText("Input data:");

        tfIn.setEditable(false);

        bChoose.setText("Choose");
        bChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChooseActionPerformed(evt);
            }
        });

        rCompress.setSelected(true);
        rCompress.setText("Compress");
        rCompress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCompressActionPerformed(evt);
            }
        });

        rDecompress.setText("Decompress");
        rDecompress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rDecompressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfIn, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bChoose))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rCompress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rDecompress)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bChoose)
                    .addComponent(tfIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rCompress)
                    .addComponent(rDecompress))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void bChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChooseActionPerformed
    system.collectOutput(this);
}//GEN-LAST:event_bChooseActionPerformed

private void rCompressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCompressActionPerformed
    rDecompress.setSelected(false);
}//GEN-LAST:event_rCompressActionPerformed

private void rDecompressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rDecompressActionPerformed
    rCompress.setSelected(false);
}//GEN-LAST:event_rDecompressActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bChoose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rCompress;
    private javax.swing.JRadioButton rDecompress;
    private javax.swing.JTextField tfIn;
    // End of variables declaration//GEN-END:variables
}
