/*
 * PAlgorithm.java
 *
 * Created on 22 March 2009, 23:13
 */
package dataanalyzer.gui;

import dataanalyzer.UserInterface;
import dataanalyzer.entity.Algorithm;
import dataanalyzer.entity.AlgorithmProcess;
import dataanalyzer.manager.GUIManager;
import dataanalyzer.util.Unique;
import java.awt.FlowLayout;
// TODO: Add settings for default display output/progress
import javax.swing.JOptionPane;
// FIXME: Dispose and preload buttons need better functionality
/**
 *
 * @author  Petah
 */
public class PAlgorithmProcess extends javax.swing.JPanel {

    private GUIManager gui;
    private Algorithm algorithm;
    private IAlgorithmPanel algorithmPanel;
    private PNode nodePanel;

    /** Creates new form PAlgorithm */
    public PAlgorithmProcess(GUIManager gui, Algorithm algorithm, PNode nodePanel) {
        this.gui = gui;
        this.algorithm = algorithm;
        this.nodePanel = nodePanel;
        initComponents();
        panel.setLayout(new FlowLayout());
        try {
            panel.add(algorithmPanel = algorithm.getGUI());
            algorithmPanel.setSystem(gui.system.userInterface);
        } catch (NullPointerException ex) {
            // FIXME: Make this error automatic close the dialog
            gui.system.userInterface.handleError("No GUI included with algorithm.", UserInterface.MAX);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        bPreload = new javax.swing.JButton();
        tfOutputName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bCancel = new javax.swing.JButton();

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        bPreload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view-refresh.png"))); // NOI18N
        bPreload.setText("Preload");
        bPreload.setToolTipText("Preload algorithm to node");
        bPreload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPreloadActionPerformed(evt);
            }
        });

        tfOutputName.setToolTipText("Set output name");

        jLabel1.setText("Output name:");

        bCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/process-stop.png"))); // NOI18N
        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bPreload)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfOutputName, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancel)
                    .addComponent(bPreload)
                    .addComponent(jLabel1)
                    .addComponent(tfOutputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void bPreloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPreloadActionPerformed
    //Collect input if the algorithm supplied a GUI
    try {
        algorithmPanel.collectInput();
    } catch (NullPointerException ex) {
    }
    AlgorithmProcess process = algorithm.createProcess();
    // FIXME: The process number wont be unique if the client has already been running
    process.setId(Unique.getLong());
    //Set the output name if applicable
    if (tfOutputName.getText().length() > 0) {
        process.setOutputName(tfOutputName.getText());
    }
    nodePanel.addProcess(process);
    gui.fmain.closeIFrame(this);
}//GEN-LAST:event_bPreloadActionPerformed

private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
    gui.fmain.closeIFrame(this);
}//GEN-LAST:event_bCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bPreload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField tfOutputName;
    // End of variables declaration//GEN-END:variables
}
