package dataanalyzer.gui;

//import dataanalyzer.CLI;
import dataanalyzer.DGA;
import java.awt.event.KeyAdapter;

/*
 * PConsole.java
 *
 * Created on 19 March 2009, 11:47
 */
import java.awt.event.KeyEvent;
import javax.swing.JScrollBar;
import javax.swing.JTextPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author  davnei06
 */
// FIXME: some times does not update right away (when using network)
public class PConsole extends javax.swing.JPanel {

    private DGA system;

    /** Creates new form PConsole */
    public PConsole(DGA system) {
        this.system = system;
        initComponents();
        textField.addKeyListener(new TFListener());
    }

    public void scrollToBottom() {
        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                JScrollBar scrollBar = scrollPane.getVerticalScrollBar();
                scrollBar.setValue(scrollBar.getMaximum());
            }
        });
    }

    public class TFListener extends KeyAdapter {

        @Override
        public void keyPressed(KeyEvent evt) {
            switch (evt.getKeyCode()) {
                case KeyEvent.VK_ENTER: {
                    //Process command
                    textPane.setText(textPane.getText() + textField.getText() + "\n");
//                    CLI.processCommand(textField.getText().split(" "), system);
                    textField.setText("");
                }
                case KeyEvent.VK_UP: {
                    //Previous command 
                }
                case KeyEvent.VK_DOWN: {
                    //Next command/blank
                }
            }
        }
    }

    public JTextPane getTextPane() {
        return textPane;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField = new javax.swing.JTextField();
        scrollPane = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane();

        textPane.setEditable(false);
        textPane.setEditorKit(new javax.swing.text.html.HTMLEditorKit());
        scrollPane.setViewportView(textPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textField, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField textField;
    private javax.swing.JTextPane textPane;
    // End of variables declaration//GEN-END:variables
}
