/*
 * PGraphMenu.java
 *
 * Created on 2 April 2009, 20:57
 */

package dataanalyzer.gui;

/**
 *
 * @author  Petah
 */
public class PGraphMenu extends javax.swing.JFrame {

    /** Creates new form PGraphMenu */
    public PGraphMenu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        mData = new javax.swing.JMenu();
        iAdd = new javax.swing.JMenuItem();
        iScale = new javax.swing.JMenuItem();
        iStep = new javax.swing.JMenuItem();
        mView = new javax.swing.JMenu();
        iBar = new javax.swing.JMenuItem();
        iLine = new javax.swing.JMenuItem();
        iArea = new javax.swing.JMenuItem();
        iPie = new javax.swing.JMenuItem();
        iData = new javax.swing.JMenuItem();
        iInformation = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mData.setText("Data");

        iAdd.setText("Add Output");
        iAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iAddActionPerformed(evt);
            }
        });
        mData.add(iAdd);

        iScale.setText("Set Scale");
        iScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iScaleActionPerformed(evt);
            }
        });
        mData.add(iScale);

        iStep.setText("Set Step");
        iStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iStepActionPerformed(evt);
            }
        });
        mData.add(iStep);

        menuBar.add(mData);

        mView.setText("View");

        iBar.setText("Bar Chart");
        iBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iBarActionPerformed(evt);
            }
        });
        mView.add(iBar);

        iLine.setText("Line Chart");
        iLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iLineActionPerformed(evt);
            }
        });
        mView.add(iLine);

        iArea.setText("Area Chart");
        iArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iAreaActionPerformed(evt);
            }
        });
        mView.add(iArea);

        iPie.setText("Pie Chart");
        iPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iPieActionPerformed(evt);
            }
        });
        mView.add(iPie);

        iData.setText("Data List");
        iData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iDataActionPerformed(evt);
            }
        });
        mView.add(iData);

        iInformation.setText("Information");
        iInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iInformationActionPerformed(evt);
            }
        });
        mView.add(iInformation);

        menuBar.add(mView);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void iAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iAddActionPerformed
}//GEN-LAST:event_iAddActionPerformed

private void iBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iBarActionPerformed
}//GEN-LAST:event_iBarActionPerformed

private void iLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iLineActionPerformed
}//GEN-LAST:event_iLineActionPerformed

private void iAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iAreaActionPerformed
}//GEN-LAST:event_iAreaActionPerformed

private void iPieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iPieActionPerformed
}//GEN-LAST:event_iPieActionPerformed

private void iDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iDataActionPerformed
}//GEN-LAST:event_iDataActionPerformed

private void iScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iScaleActionPerformed
}//GEN-LAST:event_iScaleActionPerformed

private void iInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iInformationActionPerformed
}//GEN-LAST:event_iInformationActionPerformed

private void iStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iStepActionPerformed
}//GEN-LAST:event_iStepActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PGraphMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem iAdd;
    private javax.swing.JMenuItem iArea;
    private javax.swing.JMenuItem iBar;
    private javax.swing.JMenuItem iData;
    private javax.swing.JMenuItem iInformation;
    private javax.swing.JMenuItem iLine;
    private javax.swing.JMenuItem iPie;
    private javax.swing.JMenuItem iScale;
    private javax.swing.JMenuItem iStep;
    private javax.swing.JMenu mData;
    private javax.swing.JMenu mView;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
