/*
 * PSettings.java
 *
 * Created on 1 April 2009, 00:08
 */
package dataanalyzer.gui;

import dataanalyzer.UserInterface;
import dataanalyzer.entity.Setting;
import dataanalyzer.listeners.ManagerUpdateListener;
import dataanalyzer.manager.GUIManager;
import dataanalyzer.manager.Manager;
import dataanalyzer.util.LookAndFeelSetter;
import java.util.Iterator;
// TODO: Make memory customizable
// TODO: Make reset button work
// TODO: Update server customize
/**
 *
 * @author  Petah
 */
public class PSettings extends javax.swing.JPanel implements ManagerUpdateListener {

    private GUIManager gui;

    /** Creates new form PSettings */
    public PSettings(GUIManager gui) {
        this.gui = gui;
        initComponents();

        switch (gui.system.userInterface.getVerbosity()) {
            case UserInterface.NONE:
                cbVerbosity.setSelectedIndex(0);
                break;
            case UserInterface.MIN:
                cbVerbosity.setSelectedIndex(1);
                break;
            case UserInterface.MAX:
                cbVerbosity.setSelectedIndex(2);
                break;
            case UserInterface.ALL:
                cbVerbosity.setSelectedIndex(3);
                break;
        }

        updateDirectorys();
    }

    private void updateDirectorys() {
        tfPluginDir.setText((String) gui.system.settingsManager.find("pluginDirectory").value);
        tfExtractedPluginDir.setText((String) gui.system.settingsManager.find("algorithmDirectory").value);
        tfUpdateDir.setText((String) gui.system.settingsManager.find("updateDirectory").value);
    }

    public void update(Manager m) {
        updateDirectorys();
    }

    private void restartApplication() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        pDirectorys = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfPluginDir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfExtractedPluginDir = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfUpdateDir = new javax.swing.JTextField();
        bSetDirs = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bResetPosition = new javax.swing.JButton();
        bResetSize = new javax.swing.JButton();
        bResetOpen = new javax.swing.JButton();
        cbLookAndFeel = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        bSetLookAndFeel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbVerbosity = new javax.swing.JComboBox();

        jLabel1.setText("Plugins");

        jLabel2.setText("Extracted Plugins");

        jLabel10.setText("Updates");

        bSetDirs.setText("Set Directorys");
        bSetDirs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSetDirsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDirectorysLayout = new javax.swing.GroupLayout(pDirectorys);
        pDirectorys.setLayout(pDirectorysLayout);
        pDirectorysLayout.setHorizontalGroup(
            pDirectorysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDirectorysLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDirectorysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDirectorysLayout.createSequentialGroup()
                        .addGroup(pDirectorysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pDirectorysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfUpdateDir, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(tfPluginDir, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(tfExtractedPluginDir, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)))
                    .addComponent(bSetDirs))
                .addContainerGap())
        );
        pDirectorysLayout.setVerticalGroup(
            pDirectorysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDirectorysLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDirectorysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfPluginDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDirectorysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfExtractedPluginDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDirectorysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfUpdateDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(bSetDirs)
                .addContainerGap())
        );

        tabbedPane.addTab("Directorys", pDirectorys);

        jCheckBox1.setText("Start Maximised");

        jLabel3.setText("Window Position");

        jLabel4.setText("Window Size");

        jLabel5.setText("X:");

        jLabel6.setText("Y:");

        jLabel7.setText("Width:");

        jLabel8.setText("Height:");

        bResetPosition.setText("Reset frame positions");
        bResetPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetPositionActionPerformed(evt);
            }
        });

        bResetSize.setText("Reset frame sizes");
        bResetSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetSizeActionPerformed(evt);
            }
        });

        bResetOpen.setText("Reset open frames");
        bResetOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetOpenActionPerformed(evt);
            }
        });

        cbLookAndFeel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Windows", "Apple", "Motif", "Metal", "Windows (Classic)" }));

        jLabel9.setText("Look and Feel");

        bSetLookAndFeel.setText("Set");
        bSetLookAndFeel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSetLookAndFeelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)))
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bResetPosition)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bResetSize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bResetOpen))
                    .addComponent(jCheckBox1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbLookAndFeel, 0, 258, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSetLookAndFeel)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(bSetLookAndFeel)
                    .addComponent(cbLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bResetPosition)
                    .addComponent(bResetSize)
                    .addComponent(bResetOpen))
                .addContainerGap())
        );

        tabbedPane.addTab("Windows", jPanel1);

        jLabel11.setText("Memory");

        jButton2.setText("Set");

        jButton3.setText("Reset Settings");

        jLabel12.setText("Update Server");

        jLabel13.setText("Verbosity");

        cbVerbosity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Minimum", "Maximum", "All" }));
        cbVerbosity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVerbosityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                            .addComponent(cbVerbosity, 0, 315, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jButton2)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbVerbosity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        tabbedPane.addTab("Program", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void bResetOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetOpenActionPerformed
    Iterator<String> i = gui.system.settingsManager.get().keySet().iterator();
    while (i.hasNext()) {
        String key = i.next();
        if (key.startsWith("frameOpen:")) {
            i.remove();
        }
    }
}//GEN-LAST:event_bResetOpenActionPerformed

private void bResetSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetSizeActionPerformed
    Iterator<String> i = gui.system.settingsManager.get().keySet().iterator();
    while (i.hasNext()) {
        String key = i.next();
        if (key.startsWith("frameSize:")) {
            i.remove();
        }
    }
}//GEN-LAST:event_bResetSizeActionPerformed

private void bResetPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetPositionActionPerformed
    Iterator<String> i = gui.system.settingsManager.get().keySet().iterator();
    while (i.hasNext()) {
        String key = i.next();
        if (key.startsWith("framePosition:")) {
            i.remove();
        }
    }
}//GEN-LAST:event_bResetPositionActionPerformed

private void bSetLookAndFeelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSetLookAndFeelActionPerformed
    String sel = (String) cbLookAndFeel.getSelectedItem();
    gui.system.settingsManager.add(new Setting<String>("lookAndFeel", sel, "String"));
    LookAndFeelSetter.parse(sel, gui);
}//GEN-LAST:event_bSetLookAndFeelActionPerformed

private void cbVerbosityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVerbosityActionPerformed
    String string = (String) cbVerbosity.getSelectedItem();
    if (string.equals("None")) {
        gui.system.userInterface.setVerbosity(UserInterface.NONE);
    }
    if (string.equals("Minimum")) {
        gui.system.userInterface.setVerbosity(UserInterface.MIN);
    }
    if (string.equals("Maximum")) {
        gui.system.userInterface.setVerbosity(UserInterface.MAX);
    }
    if (string.equals("All")) {
        gui.system.userInterface.setVerbosity(UserInterface.ALL);
    }
    gui.system.settingsManager.add(new Setting<Integer>("verbosity", gui.system.userInterface.getVerbosity(), "Integer"));
}//GEN-LAST:event_cbVerbosityActionPerformed

private void bSetDirsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSetDirsActionPerformed
    gui.system.settingsManager.add(new Setting<String>("algorithmDirectory", tfExtractedPluginDir.getText(), "String"));
    gui.system.settingsManager.add(new Setting<String>("pluginDirectory", tfPluginDir.getText(), "String"));
    gui.system.settingsManager.add(new Setting<String>("updateDirectory", tfUpdateDir.getText(), "String"));
}//GEN-LAST:event_bSetDirsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bResetOpen;
    private javax.swing.JButton bResetPosition;
    private javax.swing.JButton bResetSize;
    private javax.swing.JButton bSetDirs;
    private javax.swing.JButton bSetLookAndFeel;
    private javax.swing.JComboBox cbLookAndFeel;
    private javax.swing.JComboBox cbVerbosity;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel pDirectorys;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField tfExtractedPluginDir;
    private javax.swing.JTextField tfPluginDir;
    private javax.swing.JTextField tfUpdateDir;
    // End of variables declaration//GEN-END:variables
}
