/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PFlater.java
 *
 * Created on 7/06/2009, 21:52:49
 */
package standard;

import compression.util.CompressionTask;
import dataanalyzer.gui.IAlgorithmPanel;
import dataanalyzer.listeners.SystemListener;

/**
 *
 * @author davnei06
 */
public class PFlater extends IAlgorithmPanel implements SystemListener {

    private Flater flater;
    private Object input;

    /** Creates new form PFlater */
    public PFlater(Flater flater) {
        this.flater = flater;
        initComponents();
    }

    @Override
    public void collectInput() {
        flater.dispose();
        if (rCompress.isSelected()) {
            flater.collectInput(CompressionTask.COMPRESS);
        } else {
            flater.collectInput(CompressionTask.DECOMPRESS);
        }
        flater.collectInput(input);
    }

    public void collectObject(Object o) {
        input = o;
        tfIn.setText(input.toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bChoose = new javax.swing.JButton();
        tfIn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rCompress = new javax.swing.JRadioButton();
        rDecompress = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("De/Inflater");

        bChoose.setText("Choose");
        bChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChooseActionPerformed(evt);
            }
        });

        tfIn.setEditable(false);

        jLabel2.setText("Input data:");

        rCompress.setSelected(true);
        rCompress.setText("Deflate");
        rCompress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCompressActionPerformed(evt);
            }
        });

        rDecompress.setText("Inflate");
        rDecompress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rDecompressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfIn, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bChoose))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rCompress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rDecompress))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bChoose)
                    .addComponent(tfIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rCompress)
                    .addComponent(rDecompress))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChooseActionPerformed
        system.collectOutput(this);
}//GEN-LAST:event_bChooseActionPerformed

    private void rCompressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCompressActionPerformed
        rDecompress.setSelected(false);
}//GEN-LAST:event_rCompressActionPerformed

    private void rDecompressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rDecompressActionPerformed
        rCompress.setSelected(false);
}//GEN-LAST:event_rDecompressActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bChoose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rCompress;
    private javax.swing.JRadioButton rDecompress;
    private javax.swing.JTextField tfIn;
    // End of variables declaration//GEN-END:variables
}
