/*
 * PWaveForm.java
 *
 * Created on 25 March 2009, 01:32
 */
package waveform;

import dataanalyzer.gui.IAlgorithmPanel;

/**
 *
 * @author  Petah
 */
public class PWaveForm extends IAlgorithmPanel {

    private WaveForm waveForm;

    /** Creates new form PPseudoRandom */
    public PWaveForm(WaveForm waveForm) {
        this.waveForm = waveForm;
        initComponents();
    }

    public void collectInput() {
        waveForm.dispose();
        waveForm.collectInput(Double.valueOf(tfStart.getText()));
        waveForm.collectInput(Double.valueOf(tfEnd.getText()));
        waveForm.collectInput(Double.valueOf(tfStep.getText()));
        String s = (String) cbType.getSelectedItem();
        WaveForm.Type type = null;
        if (s.equals("Sine")) {
            type = WaveForm.Type.SIN;
        } else if (s.equals("Cosine")) {
            type = WaveForm.Type.COS;
        } else if (s.equals("Tangent")) {
            type = WaveForm.Type.TAN;
        }
        waveForm.collectInput(type);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lTitle = new javax.swing.JLabel();
        lStart = new javax.swing.JLabel();
        lEnd = new javax.swing.JLabel();
        lType = new javax.swing.JLabel();
        tfStart = new javax.swing.JTextField();
        tfEnd = new javax.swing.JTextField();
        cbType = new javax.swing.JComboBox();
        lStep = new javax.swing.JLabel();
        tfStep = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        lTitle.setFont(new java.awt.Font("Tahoma", 0, 36));
        lTitle.setText("Wave Form");

        lStart.setText("Start value:");

        lEnd.setText("End value:");

        lType.setText("Type:");

        tfStart.setText("1");

        tfEnd.setText("10");

        cbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sine", "Cosine", "Tangent" }));

        lStep.setText("Step:");

        tfStep.setText("0.001");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lStart)
                            .addComponent(lEnd)
                            .addComponent(lStep)
                            .addComponent(lType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbType, 0, 319, Short.MAX_VALUE)
                            .addComponent(tfStep, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(tfEnd, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(tfStart, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStart)
                    .addComponent(tfStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEnd)
                    .addComponent(tfEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStep)
                    .addComponent(tfStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lType)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbType;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lEnd;
    private javax.swing.JLabel lStart;
    private javax.swing.JLabel lStep;
    private javax.swing.JLabel lTitle;
    private javax.swing.JLabel lType;
    private javax.swing.JTextField tfEnd;
    private javax.swing.JTextField tfStart;
    private javax.swing.JTextField tfStep;
    // End of variables declaration//GEN-END:variables
}
